project_name: whatfs

before:
  hooks:
    - go mod tidy

builds:
  - binary: whatfs
    env: []
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

release:
  prerelease: auto
